services:
  - type: worker
    name: minestrator-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SERVER_URL
        sync: false
      - key: COOKIE_PHPSESSID
        sync: false
      - key: COOKIE_API_KEY
        sync: false
      - key: COOKIE_AUTH_STATE
        sync: false
      - key: COOKIE_CW
        sync: false
