services:
  - type: worker
    name: minestrator-bot
    env: node
    buildCommand: npm install && PUPPETEER_CACHE_DIR=/opt/render/project/src/.cache/puppeteer node_modules/.bin/puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: MINESTRATOR_EMAIL
        sync: false
      - key: MINESTRATOR_PASSWORD
        sync: false
      - key: SERVER_URL
        sync: false
      - key: COOKIE_PHPSESSID
        sync: false
      - key: COOKIE_API_KEY
        sync: false
      - key: COOKIE_AUTH_STATE
        sync: false
      - key: COOKIE_CW
        sync: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer